const COLLEGES = {
  "SAFA College": {
    "UG First Year": ["BCOM CA","BCA","BBA","BCOM FIN","BSW","BAMC","GEOGRAPHY","ENGLISH","BAEFT","PSYCHOLOGY","MICRO BIOLOGY"],
    "UG Second Year": ["BCOM CA","BCA","BBA","BCOM FIN","BSW","BAMC","GEOGRAPHY","ENGLISH","BAEFT","PSYCHOLOGY","MICRO BIOLOGY"],
    "UG Third Year": ["BCOM CA","BCA","BBA","BCOM FIN","BSW","BAMC","GEOGRAPHY","ENGLISH","BAEFT","PSYCHOLOGY"],
    "PG First Year": ["MA ENGLISH","MCOM","MA ECONOMICS"],
    "PG Second Year": ["MA ENGLISH","MCOM","MA ECONOMICS"]
  },
  "Majlis College": {},
  "KRSN College": {
    "UG First Year": ["BCOM FINANCE","BCOM CA","BCA","BBA","BA ECO","BA ENGLISH","PSYCHOLOGY","GEOLOGY","BSW"],
    "UG Second Year": ["BCOM FINANCE","BCOM CA","BCA","BBA","BA ECO","PSYCHOLOGY","GEOLOGY","BSW"],
    "UG Third Year": ["BCOM FINANCE","BCOM CA","BCA","BBA","BA ECO","BA ENGLISH","PSYCHOLOGY","GEOLOGY"],
    "PG First Year": ["MSC PSYCHOLOGY"],
    "PG Second Year": ["MSC PSYCHOLOGY"]
  },
  "MES KVM College": {
    "UG First Year": ["B.COM FINANCE","B.COM CA","B.COM SF","PHYSICS","CHEMISTRY","BCA","ZOOLOGY","BOTANY","PSYCHOLOGY","BVOC RETAIL","BVOC OPTO","BAFE"],
    "UG Second Year": ["B.COM FINANCE","B.COM CA","B.COM SF","PHYSICS","CHEMISTRY","BCA","ZOOLOGY","BOTANY","PSYCHOLOGY","BVOC RETAIL","BVOC OPTO","BAFE"],
    "UG Third Year": ["B.COM FINANCE","B.COM CA","B.COM SF","PHYSICS","CHEMISTRY","BCA","ZOOLOGY","BOTANY","PSYCHOLOGY","BVOC RETAIL","BVOC OPTO","BAFE"],
    "PG First Year": ["MCOM","MSC PHYSICS","MSC COMPUTER SCIENCE","MSC POLYMER CHEMISTRY","MA ENGLISH","MSC ZOOLOGY","MSC PSYCHOLOGY","MSC BOTANY"],
    "PG Second Year": ["MCOM","MSC PHYSICS","MSC COMPUTER SCIENCE","MSC POLYMER CHEMISTRY","MA ENGLISH","MSC ZOOLOGY","MSC BOTANY"]
  },
  "KMCT Law College": {},
  "CPA College": {}
};

const MANUAL_OPTION = "__manual__";